name: spacera
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  test: flutter test
  analyze: flutter analyze --no-pub
  format: flutter format lib/**

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.0.1

  # Network
  dio: ^4.0.4

  # Utilities
  logging: ^1.0.2
  get_it: ^7.2.0
  url_launcher: ^6.1.10
  retry: ^3.1.0
  connectivity_plus: ^3.0.3

  # DB
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.2.0

  # Ui
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

  # Firebase
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^8.2.0
  build_runner: ^2.1.10
  hive_generator: ^2.0.0
  logger: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: sinkinsans
      fonts:
        - asset: assets/fonts/SinkinSansRegular.otf
          weight: 400
        - asset: assets/fonts/SinkinSansThin.otf
          weight: 100
        - asset: assets/fonts/SinkinSansBold.otf
          weight: 700

    - family: spacex
      fonts:
        - asset: assets/fonts/SpaceX.ttf